language: node_js
node_js:
  - 8
  - 10

env:
  matrix:
    - MONGODB=3.4.16
    - MONGODB=3.6.6
    - MONGODB=4.0.1

matrix:
  fast_finish: true

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - if [[ "5.0.0" > `npm -v` ]]; then npm i -g npm@5; fi

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

script:
  - npm run coverage -- --no-cache --runInBand

after_success:
  - npm run coverage:report
